### ISSUE TITLE
椭圆功能使用

### ISSUE THREAD

**Issue by AI4CT** [Angelo-scut/Labelme-improved#1]
更新了labelme_local后报错：
ModuleNotFoundError: No module named 'labelme_local.cython.mylivewire'
请问是什么问题？

**Comment by AI4CT** [comment]
用的是vscode

**Comment by Angelo-scut** [comment]
稍等哈，我再测试一下，因为我这边测试没有问题，我看看是否需要再添加一个sys.path

**Comment by Angelo-scut** [comment]
我测试了不同环境的，发现在python3.9的是存在类似问题的，因为我改的时候用的是python3.7。可能是python版本不一样导致的，你可以试试新建一个python3.7的环境？

**Comment by Angelo-scut** [comment]
另外，在pycharm中python3.9也是没有问题的，我觉得可能是sys.path设置不太一样导致的吧，pycharm它会自动索引当前项目。

**Comment by Angelo-scut** [comment]
刚刚在师弟的电脑vs code上测试了一下，发现使用Run code的时候也无法正确import，仔细看了一下发现conda环境没有被激活，需要Run python file才会自动激活conda环境。希望有用。。我的coding能力也很拉。

**Comment by AI4CT** [comment]
我的conda环境已经确认激活了，我看了一下 报错在mylivewire.cpp第23行：#include "Python.h"，提示：无法打开 源 文件 "Python.h"，应该是我的环境设置问题，我再检查一下，谢谢！

**Comment by Angelo-scut** [comment]
需要确定一下cython是否安装，或者安装和我一样cython版本，cython==0.29.24

**Comment by AI4CT** [comment]
调试成功了 之前用的python3.8 怎么都不行 换成python3.7之后畅通无阻
